import React from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar'
import AuthProvider from './AuthProvider'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <main>
            <Navbar></Navbar>
          </main>

          {children}
        </body>
      </html>
    </AuthProvider>
  )
}
